version: '2'
services:
    jhipsterapp-app:
        image: jhipsterapp
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jhipsterapp-mysql:3306/jhipsterapp?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhipsterapp-mysql:
        extends:
            file: mysql.yml
            service: jhipsterapp-mysql
